### ISSUE TITLE
Server hang

### ISSUE THREAD

**Issue by jeffmendoza** [microsoftarchive/http2-katana#14]
The https server hung over the night. Log below.
8am machine = 1am west coast = 10am Germany time

```
[8/4/2013 8:24:26 AM] ThreadId:6 DBG:New connection accepted
[8/4/2013 8:24:32 AM] ThreadId:32 ERROR:Handshake timeout. Connection dropped.
[8/4/2013 8:24:41 AM] ThreadId:6 DBG:New connection accepted
[8/4/2013 8:24:47 AM] ThreadId:32 ERROR:Handshake timeout. Connection dropped.
[8/4/2013 8:24:56 AM] ThreadId:6 DBG:New connection accepted
[8/4/2013 8:25:02 AM] ThreadId:32 ERROR:Handshake timeout. Connection dropped.
[8/4/2013 8:25:02 AM] ThreadId:6 DBG:New connection accepted
[8/4/2013 8:25:06 AM] ThreadId:32 DBG:Handshake successful
[8/4/2013 8:25:06 AM] ThreadId:32 DBG:Session start
[8/4/2013 8:25:06 AM] ThreadId:30 DBG:Settings frame. Entry count: 1 StreamId: 0
[8/4/2013 8:25:06 AM] ThreadId:30 DBG:WindowUpdate frame. Delta: 268369921 StreamId: 0
[8/4/2013 8:25:06 AM] ThreadId:30 DBG:New headers with id = 1
[8/4/2013 8:25:06 AM] ThreadId:30 DBG:Final frame received for stream with id = 1
[8/4/2013 8:25:06 AM] ThreadId:30 DBG:Transfer begin
[8/4/2013 8:25:06 AM] ThreadId:30 DBG:Transfer end
[8/4/2013 8:25:06 AM] ThreadId:30 DBG:Total outgoing data frames volume 335
[8/4/2013 8:25:06 AM] ThreadId:30 DBG:Stream closed 1
[8/4/2013 8:25:06 AM] ThreadId:30 DBG:WindowUpdate frame. Delta: 0 StreamId: 1
[8/4/2013 8:25:11 AM] ThreadId:6 DBG:New connection accepted
[8/4/2013 8:25:26 AM] ThreadId:6 DBG:New connection accepted
[8/4/2013 8:25:41 AM] ThreadId:6 DBG:New connection accepted
```

**Comment by akalin-chromium** [comment]
The server hung again just now.

**Comment by jeffmendoza** [comment]
log again

```
[8/5/2013 2:44:11 AM] ThreadId:6 DBG:New connection accepted
[8/5/2013 2:44:17 AM] ThreadId:57 ERROR:Handshake timeout. Connection dropped.
[8/5/2013 2:44:22 AM] ThreadId:6 DBG:New connection accepted
[8/5/2013 2:44:22 AM] ThreadId:6 DBG:New connection accepted
[8/5/2013 2:44:22 AM] ThreadId:57 ERROR:Client has wrong session header. It was disconnected
[8/5/2013 2:44:24 AM] ThreadId:39 DBG:Handshake successful
[8/5/2013 2:44:24 AM] ThreadId:39 DBG:Session start
[8/5/2013 2:44:24 AM] ThreadId:57 DBG:Settings frame. Entry count: 2 StreamId: 0
[8/5/2013 2:44:24 AM] ThreadId:57 DBG:WindowUpdate frame. Delta: 10420224 StreamId: 0
[8/5/2013 2:44:24 AM] ThreadId:57 DBG:New headers with id = 1
[8/5/2013 2:44:24 AM] ThreadId:57 DBG:Final frame received for stream with id = 1
[8/5/2013 2:44:24 AM] ThreadId:57 DBG:Transfer begin
[8/5/2013 2:44:24 AM] ThreadId:57 DBG:Transfer end
[8/5/2013 2:44:24 AM] ThreadId:57 DBG:Total outgoing data frames volume 335
[8/5/2013 2:44:24 AM] ThreadId:57 DBG:Stream closed 1
[8/5/2013 2:44:25 AM] ThreadId:57 DBG:New headers with id = 3
[8/5/2013 2:44:25 AM] ThreadId:57 DBG:Final frame received for stream with id = 3
[8/5/2013 2:44:25 AM] ThreadId:57 DBG:Transfer begin
[8/5/2013 2:44:25 AM] ThreadId:57 DBG:Transfer end
[8/5/2013 2:44:25 AM] ThreadId:57 DBG:Total outgoing data frames volume 335
[8/5/2013 2:44:25 AM] ThreadId:57 DBG:Stream closed 3
[8/5/2013 2:44:26 AM] ThreadId:6 DBG:New connection accepted
[8/5/2013 2:44:41 AM] ThreadId:6 DBG:New connection accepted
```

**Comment by jeffmendoza** [comment]
Restarted

**Comment by akalin-chromium** [comment]
Hung again just now.

**Comment by squirrelfm** [comment]
This may be realted to ping, I've fixed one ping related hung. It is hard to tell though so will not close the bug for now. Need to monitor client for couple of days.

**Comment by akalin-chromium** [comment]
Should it not be hung anymore? I just tried it and it still hangs...

**Comment by squirrelfm** [comment]
Not deployed any fixes yet)

**Comment by akalin-chromium** [comment]
Can you at least restart the server, so I can continue testing?

**Comment by squirrelfm** [comment]
Changes redeployed and restarted
